author: Spice King
database: false
description: Provides a provides a display on the client of the current balance. Requires
  Spout (formerly BukkitContrib) plugin and mod.
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.spiceking.plugins.spoutwallet.SpoutWallet
name: SpoutWallet
startup: postworld
depend: [Spout, Vault]
version: ${pom.version}-${git.commit.id.abbrev} built ${git.build.time}
commands:
  wallet:
    description: Toggles the Spout-based display of the money they are holding
    usage: /<command>
permissions:
    SpoutWallet.*:
        description: Users can see and toggle the display
        default: true
        children:
            SpoutWallet.Use: true
            SpoutWallet.Toggle: true
    SpoutWallet.Use:
        description: Users can see the display
        default: true
    SpoutWallet.Toggle:
        description: Users can toggle the display
        default: true